"""new fields for drug index

Revision ID: 1681f02fd8c1
Revises: b9ccd548d410
Create Date: 2026-06-13 16:53:44.431908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1681f02fd8c1'
down_revision: Union[str, Sequence[str], None] = 'b9ccd548d410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_index', sa.Column('ndc_codes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('drug_index', sa.Column('upc_codes', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_column('drug_index', 'openfda_meta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_index', sa.Column('openfda_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('drug_index', 'upc_codes')
    op.drop_column('drug_index', 'ndc_codes')
    # ### end Alembic commands ###
