"""re added webhook billing

Revision ID: 1e346c487492
Revises: aac4006b6247
Create Date: 2026-07-02 10:47:11.922016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e346c487492'
down_revision: Union[str, Sequence[str], None] = 'aac4006b6247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_limits_id'), table_name='usage_limits')
    op.drop_table('usage_limits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_limits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('feature_key', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('free_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('usage_limits_updated_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usage_limits_pkey')),
    sa.UniqueConstraint('feature_key', name=op.f('usage_limits_feature_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_usage_limits_id'), 'usage_limits', ['id'], unique=False)
    # ### end Alembic commands ###
