"""added subscription support to user

Revision ID: 23e584c590b9
Revises: 5f6490793ccc
Create Date: 2026-06-17 11:11:48.245784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23e584c590b9'
down_revision: Union[str, Sequence[str], None] = '5f6490793ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('plan', sa.String(length=30), server_default='free', nullable=False))
    op.add_column('user_subscriptions', sa.Column('provider', sa.String(length=30), server_default='manual', nullable=False))
    op.add_column('user_subscriptions', sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_subscriptions', sa.Column('granted_by_admin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_subscriptions', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_subscriptions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('user_subscriptions', 'current_period_end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('user_subscriptions', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('user_subscriptions_user_id_key'), 'user_subscriptions', type_='unique')
    op.create_index(op.f('ix_user_subscriptions_stripe_customer_id'), 'user_subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_stripe_subscription_id'), 'user_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_stripe_subscription_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_stripe_customer_id'), table_name='user_subscriptions')
    op.create_unique_constraint(op.f('user_subscriptions_user_id_key'), 'user_subscriptions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_subscriptions', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_subscriptions', 'current_period_end',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('user_subscriptions', 'updated_at')
    op.drop_column('user_subscriptions', 'created_at')
    op.drop_column('user_subscriptions', 'notes')
    op.drop_column('user_subscriptions', 'granted_by_admin')
    op.drop_column('user_subscriptions', 'current_period_start')
    op.drop_column('user_subscriptions', 'provider')
    op.drop_column('user_subscriptions', 'plan')
    # ### end Alembic commands ###
