"""removed latest id from detail

Revision ID: 273f11283209
Revises: d4d62239362c
Create Date: 2025-12-02 17:38:34.973196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273f11283209'
down_revision: Union[str, Sequence[str], None] = 'd4d62239362c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('drug_details_latest_detail_id_fkey'), 'drug_details', type_='foreignkey')
    op.drop_column('drug_details', 'latest_detail_id')
    op.drop_constraint(op.f('fk_drug_index_latest_detail'), 'drug_index', type_='foreignkey')
    op.drop_column('drug_index', 'latest_detail_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_index', sa.Column('latest_detail_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_drug_index_latest_detail'), 'drug_index', 'drug_details', ['latest_detail_id'], ['id'], ondelete='SET NULL')
    op.add_column('drug_details', sa.Column('latest_detail_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('drug_details_latest_detail_id_fkey'), 'drug_details', 'drug_details', ['latest_detail_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
