"""added status field to object

Revision ID: 27720ae98f38
Revises: 60b6562bbba4
Create Date: 2026-07-14 15:52:04.811186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27720ae98f38'
down_revision: Union[str, Sequence[str], None] = '60b6562bbba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_feedback', sa.Column('status', sa.String(length=24), nullable=False))
    op.create_index(op.f('ix_user_feedback_status'), 'user_feedback', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedback_status'), table_name='user_feedback')
    op.drop_column('user_feedback', 'status')
    # ### end Alembic commands ###
