"""agnositc user payment subscription added

Revision ID: 33f6c52a0b87
Revises: 23e584c590b9
Create Date: 2026-06-18 12:11:11.118522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33f6c52a0b87'
down_revision: Union[str, Sequence[str], None] = '23e584c590b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('provider_customer_id', sa.String(length=255), nullable=True))
    op.add_column('user_subscriptions', sa.Column('provider_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('user_subscriptions', sa.Column('provider_transaction_id', sa.String(length=255), nullable=True))
    op.add_column('user_subscriptions', sa.Column('provider_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_user_subscriptions_stripe_customer_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_stripe_subscription_id'), table_name='user_subscriptions')
    op.create_index(op.f('ix_user_subscriptions_plan'), 'user_subscriptions', ['plan'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_provider'), 'user_subscriptions', ['provider'], unique=False)
    op.create_index('ix_user_subscriptions_provider_customer', 'user_subscriptions', ['provider', 'provider_customer_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_status'), 'user_subscriptions', ['status'], unique=False)
    op.create_index('ix_user_subscriptions_user_provider', 'user_subscriptions', ['user_id', 'provider'], unique=False)
    op.create_unique_constraint('uq_user_subscription_provider_subscription', 'user_subscriptions', ['provider', 'provider_subscription_id'])
    op.drop_column('user_subscriptions', 'stripe_customer_id')
    op.drop_column('user_subscriptions', 'stripe_subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_subscriptions', sa.Column('stripe_customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_user_subscription_provider_subscription', 'user_subscriptions', type_='unique')
    op.drop_index('ix_user_subscriptions_user_provider', table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_status'), table_name='user_subscriptions')
    op.drop_index('ix_user_subscriptions_provider_customer', table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_provider'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_plan'), table_name='user_subscriptions')
    op.create_index(op.f('ix_user_subscriptions_stripe_subscription_id'), 'user_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_stripe_customer_id'), 'user_subscriptions', ['stripe_customer_id'], unique=False)
    op.drop_column('user_subscriptions', 'provider_raw')
    op.drop_column('user_subscriptions', 'provider_transaction_id')
    op.drop_column('user_subscriptions', 'provider_subscription_id')
    op.drop_column('user_subscriptions', 'provider_customer_id')
    # ### end Alembic commands ###
