"""added symptoms_table to drug_details

Revision ID: 41524d373cf5
Revises: 29170482e310
Create Date: 2026-01-21 16:11:58.833931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41524d373cf5'
down_revision: Union[str, Sequence[str], None] = '29170482e310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_details', sa.Column('symptoms_table', postgresql.ARRAY(sa.Text()), nullable=True))
    op.create_foreign_key(None, 'drug_details', 'drug_index', ['drug_index_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_medications', 'drug_details', ['drug_detail_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_medications', type_='foreignkey')
    op.drop_constraint(None, 'drug_details', type_='foreignkey')
    op.drop_column('drug_details', 'symptoms_table')
    # ### end Alembic commands ###
