"""set field size to 300 drug_index

Revision ID: 4189571a0b48
Revises: 80eda85f6a39
Create Date: 2026-04-08 16:53:01.892585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4189571a0b48'
down_revision: Union[str, Sequence[str], None] = '80eda85f6a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_index', 'name',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('drug_index', 'normalized_name',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('drug_index', 'manufacturer',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_index', 'manufacturer',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    op.alter_column('drug_index', 'normalized_name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=400),
               existing_nullable=False)
    op.alter_column('drug_index', 'name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=400),
               existing_nullable=False)
    # ### end Alembic commands ###
