"""unique drug name

Revision ID: 46700f0ef3c5
Revises: 9c7a8d75b764
Create Date: 2025-11-15 15:43:43.604812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46700f0ef3c5'
down_revision: Union[str, Sequence[str], None] = '9c7a8d75b764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_drug_index_name_kind', 'drug_index', ['normalized_name', 'kind'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_drug_index_name_kind', 'drug_index', type_='unique')
    # ### end Alembic commands ###
