"""fix relationship user medication

Revision ID: 4d93f65f7957
Revises: 4cf9f9f36848
Create Date: 2026-01-10 15:31:05.502400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d93f65f7957'
down_revision: Union[str, Sequence[str], None] = '4cf9f9f36848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1) Add column as nullable first
    op.add_column("user_medications", sa.Column("medication_id", sa.Integer(), nullable=True))

    # 2) Backfill it (choose ONE approach below)
    # A) If you can map from old drug_index_id:
    # op.execute("""
    # UPDATE user_medications um
    # SET medication_id = m.id
    # FROM medications m
    # WHERE um.drug_index_id IS NOT NULL
    #   AND m.drug_index_id = um.drug_index_id
    # """)

    # B) If you DON'T have a reliable mapping yet (dev stage):
    # Either delete rows or set a placeholder mapping strategy.
    # Example: delete existing rows so you can enforce NOT NULL:
    # op.execute("DELETE FROM user_medications")

    # 3) Now enforce NOT NULL (only if no NULLs remain)
    op.alter_column("user_medications", "medication_id", nullable=False)

    # 4) Add FK after data is valid
    op.create_foreign_key(
        "user_medications_medication_id_fkey",
        "user_medications",
        "medications",
        ["medication_id"],
        ["id"],
        ondelete="CASCADE",
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
