"""removed user med constraint

Revision ID: 690560d9b958
Revises: 99a8732e07dd
Create Date: 2026-03-12 16:25:10.807741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690560d9b958'
down_revision: Union[str, Sequence[str], None] = '99a8732e07dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_drugdetail'), 'user_medications', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_drugdetail'), 'user_medications', ['user_id', 'drug_detail_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
