"""added drug_updates

Revision ID: 6c6bf41db14e
Revises: 064bd8533e83
Create Date: 2026-04-02 11:43:13.384381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c6bf41db14e'
down_revision: Union[str, Sequence[str], None] = '064bd8533e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_name'), table_name='tests')
    op.drop_table('tests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tests_pkey'))
    )
    op.create_index(op.f('ix_tests_name'), 'tests', ['name'], unique=True)
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('route', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('side_effects', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('medications_pkey'))
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    # ### end Alembic commands ###
