"""added new field to drug detail object

Revision ID: 709ebcdf889f
Revises: 46700f0ef3c5
Create Date: 2025-11-27 01:27:35.546148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709ebcdf889f'
down_revision: Union[str, Sequence[str], None] = '46700f0ef3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_details', sa.Column('latest_detail_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drug_details', 'drug_details', ['latest_detail_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drug_details', type_='foreignkey')
    op.drop_column('drug_details', 'latest_detail_id')
    # ### end Alembic commands ###
