"""added side effect list to drug detail

Revision ID: 888c77b4b826
Revises: 95e662347ce8
Create Date: 2025-12-17 16:01:27.041393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '888c77b4b826'
down_revision: Union[str, Sequence[str], None] = '95e662347ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_details', sa.Column('side_effects', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drug_details', 'side_effects')
    # ### end Alembic commands ###
