"""added lastest id to drug index

Revision ID: 95e662347ce8
Revises: 273f11283209
Create Date: 2025-12-02 17:41:19.925317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e662347ce8'
down_revision: Union[str, Sequence[str], None] = '273f11283209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_index', sa.Column('latest_detail_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drug_index', 'drug_details', ['latest_detail_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drug_index', type_='foreignkey')
    op.drop_column('drug_index', 'latest_detail_id')
    # ### end Alembic commands ###
