"""added default recall type to user settings

Revision ID: 9930a669ccce
Revises: 6227cb4bded1
Create Date: 2026-04-30 23:04:33.767031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9930a669ccce'
down_revision: Union[str, Sequence[str], None] = '6227cb4bded1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('default_recall_type', sa.String(length=20), server_default='all', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'default_recall_type')
    # ### end Alembic commands ###
