"""added safety warning field

Revision ID: 9a02c054d5fe
Revises: 008a6524ce9c
Create Date: 2026-07-11 14:31:22.014750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a02c054d5fe'
down_revision: Union[str, Sequence[str], None] = '008a6524ce9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_details', sa.Column('safety_warnings_curated', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drug_details', 'safety_warnings_curated')
    # ### end Alembic commands ###
