"""added new fields and article object

Revision ID: 9f21c5c87b37
Revises: 8f4e682abdc3
Create Date: 2026-04-03 16:18:45.940160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f21c5c87b37'
down_revision: Union[str, Sequence[str], None] = '8f4e682abdc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_drug_updates', sa.Column('technical_title', sa.Text(), nullable=False))
    op.add_column('external_drug_updates', sa.Column('technical_drug_name', sa.Text(), nullable=True))
    op.add_column('external_drug_updates', sa.Column('display_name', sa.Text(), nullable=True))
    op.add_column('external_drug_updates', sa.Column('official_name', sa.Text(), nullable=True))
    op.add_column('external_drug_updates', sa.Column('plain_summary', sa.Text(), nullable=True))
    op.add_column('external_drug_updates', sa.Column('dailymed_url', sa.Text(), nullable=True))
    op.add_column('external_drug_updates', sa.Column('medlineplus_url', sa.Text(), nullable=True))
    op.alter_column('external_drug_updates', 'external_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_external_drug_updates_display_name'), 'external_drug_updates', ['display_name'], unique=False)
    op.create_index(op.f('ix_external_drug_updates_drug_name'), 'external_drug_updates', ['drug_name'], unique=False)
    op.create_index(op.f('ix_external_drug_updates_official_name'), 'external_drug_updates', ['official_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_drug_updates_official_name'), table_name='external_drug_updates')
    op.drop_index(op.f('ix_external_drug_updates_drug_name'), table_name='external_drug_updates')
    op.drop_index(op.f('ix_external_drug_updates_display_name'), table_name='external_drug_updates')
    op.alter_column('external_drug_updates', 'external_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('external_drug_updates', 'medlineplus_url')
    op.drop_column('external_drug_updates', 'dailymed_url')
    op.drop_column('external_drug_updates', 'plain_summary')
    op.drop_column('external_drug_updates', 'official_name')
    op.drop_column('external_drug_updates', 'display_name')
    op.drop_column('external_drug_updates', 'technical_drug_name')
    op.drop_column('external_drug_updates', 'technical_title')
    # ### end Alembic commands ###
