"""fix relationship user medication

Revision ID: a4c3a1673402
Revises: 34f68b06457f
Create Date: 2026-01-10 16:59:04.479330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c3a1673402'
down_revision: Union[str, Sequence[str], None] = '34f68b06457f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 0) Make sure this FK is named (optional but recommended)
    op.create_foreign_key(
        "drug_index_latest_detail_id_fkey",
        "drug_index",
        "drug_details",
        ["latest_detail_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # 1) Add column as NULLABLE first
    op.add_column("user_medications", sa.Column("drug_detail_id", sa.Integer(), nullable=True))

    # 2) Backfill drug_detail_id from drug_index.latest_detail_id
    # This maps existing user_medications.drug_index_id -> drug_index.latest_detail_id
    op.execute("""
        UPDATE user_medications um
        SET drug_detail_id = di.latest_detail_id
        FROM drug_index di
        WHERE um.drug_index_id = di.id
          AND um.drug_detail_id IS NULL
    """)

    # 3) If any rows couldn't be backfilled, you must decide what to do.
    # In dev, simplest is to delete them:
    op.execute("""
        DELETE FROM user_medications
        WHERE drug_detail_id IS NULL
    """)

    # 4) Now we can enforce NOT NULL
    op.alter_column("user_medications", "drug_detail_id", nullable=False)

    # 5) Drop old constraints/index on drug_index_id (must happen after backfill)
    op.drop_index(op.f("ix_user_medications_drug_index_id"), table_name="user_medications")
    op.drop_constraint(op.f("uq_user_med_start"), "user_medications", type_="unique")

    # 6) Add new index/unique/FK
    op.create_index(op.f("ix_user_medications_drug_detail_id"), "user_medications", ["drug_detail_id"], unique=False)
    op.create_unique_constraint("uq_user_drugdetail", "user_medications", ["user_id", "drug_detail_id"])
    op.create_foreign_key(
        "user_medications_drug_detail_id_fkey",
        "user_medications",
        "drug_details",
        ["drug_detail_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # 7) Finally drop old column
    op.drop_column("user_medications", "drug_index_id")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_medications', sa.Column('drug_index_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_medications', type_='foreignkey')
    op.drop_constraint('uq_user_drugdetail', 'user_medications', type_='unique')
    op.drop_index(op.f('ix_user_medications_drug_detail_id'), table_name='user_medications')
    op.create_unique_constraint(op.f('uq_user_med_start'), 'user_medications', ['user_id', 'drug_index_id', 'start_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_medications_drug_index_id'), 'user_medications', ['drug_index_id'], unique=False)
    op.drop_column('user_medications', 'drug_detail_id')
    op.drop_constraint(None, 'drug_index', type_='foreignkey')
    # ### end Alembic commands ###
