"""add billing webhook events

Revision ID: aac4006b6247
Revises: 33f6c52a0b87
Create Date: 2026-06-18 14:34:12.878744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aac4006b6247'
down_revision: Union[str, Sequence[str], None] = '33f6c52a0b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_billing_webhook_provider_event')
    )
    op.create_index(op.f('ix_billing_webhook_events_event_type'), 'billing_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_billing_webhook_events_id'), 'billing_webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_billing_webhook_events_provider'), 'billing_webhook_events', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_webhook_events_provider'), table_name='billing_webhook_events')
    op.drop_index(op.f('ix_billing_webhook_events_id'), table_name='billing_webhook_events')
    op.drop_index(op.f('ix_billing_webhook_events_event_type'), table_name='billing_webhook_events')
    op.drop_table('billing_webhook_events')
    # ### end Alembic commands ###
