"""added recall object

Revision ID: ac87d65fd581
Revises: af3ed030c351
Create Date: 2026-04-20 15:36:27.820620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac87d65fd581'
down_revision: Union[str, Sequence[str], None] = 'af3ed030c351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_medications', 'drug_index', ['drug_index_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_medications', 'drug_details', ['drug_detail_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_medications', type_='foreignkey')
    op.drop_constraint(None, 'user_medications', type_='foreignkey')
    # ### end Alembic commands ###
