"""updated drug detail fields

Revision ID: af3ed030c351
Revises: 4189571a0b48
Create Date: 2026-04-09 21:56:02.449149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3ed030c351'
down_revision: Union[str, Sequence[str], None] = '4189571a0b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'symptom_logs', 'user_medications', ['user_medication_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'symptom_logs', type_='foreignkey')
    # ### end Alembic commands ###
