"""add track purpose field for user med obj

Revision ID: b9ccd548d410
Revises: c1a67f81a010
Create Date: 2026-05-13 14:07:32.194950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ccd548d410'
down_revision: Union[str, Sequence[str], None] = 'c1a67f81a010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_medications', sa.Column('tracking_purpose', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_medications', 'tracking_purpose')
    # ### end Alembic commands ###
