"""added two fields to symptom logs

Revision ID: c1a67f81a010
Revises: 9930a669ccce
Create Date: 2026-05-10 21:23:59.801953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a67f81a010'
down_revision: Union[str, Sequence[str], None] = '9930a669ccce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symptom_logs', sa.Column('possible_trigger', sa.String(length=120), nullable=True))
    op.add_column('symptom_logs', sa.Column('management_strategy', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symptom_logs', 'management_strategy')
    op.drop_column('symptom_logs', 'possible_trigger')
    # ### end Alembic commands ###
