"""edited user medication

Revision ID: c473ad8c23a7
Revises: f404885616fd
Create Date: 2026-01-10 15:17:24.994237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c473ad8c23a7'
down_revision: Union[str, Sequence[str], None] = 'f404885616fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_medications', sa.Column('drug_index_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_user_medications_medication_id'), table_name='user_medications')
    op.drop_constraint(op.f('uq_user_med_start'), 'user_medications', type_='unique')
    op.create_unique_constraint('uq_user_med_start', 'user_medications', ['user_id', 'drug_index_id', 'start_date'])
    op.create_index(op.f('ix_user_medications_drug_index_id'), 'user_medications', ['drug_index_id'], unique=False)
    op.drop_constraint(op.f('user_medications_medication_id_fkey'), 'user_medications', type_='foreignkey')
    op.create_foreign_key(None, 'user_medications', 'drug_index', ['drug_index_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('user_medications', 'medication_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_medications', sa.Column('medication_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_medications', type_='foreignkey')
    op.create_foreign_key(op.f('user_medications_medication_id_fkey'), 'user_medications', 'medications', ['medication_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_user_medications_drug_index_id'), table_name='user_medications')
    op.drop_constraint('uq_user_med_start', 'user_medications', type_='unique')
    op.create_unique_constraint(op.f('uq_user_med_start'), 'user_medications', ['user_id', 'medication_id', 'start_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_medications_medication_id'), 'user_medications', ['medication_id'], unique=False)
    op.drop_column('user_medications', 'drug_index_id')
    # ### end Alembic commands ###
