"""updated usersaveditem

Revision ID: c6804602c2cd
Revises: 141e1276164b
Create Date: 2026-04-22 11:16:43.148335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6804602c2cd'
down_revision: Union[str, Sequence[str], None] = '141e1276164b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_saved_items_id'), 'user_saved_items', ['id'], unique=False)
    op.create_index('ix_user_saved_items_user_content', 'user_saved_items', ['user_id', 'content_type'], unique=False)
    op.drop_constraint(op.f('user_saved_items_user_id_fkey'), 'user_saved_items', type_='foreignkey')
    op.create_foreign_key(None, 'user_saved_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_saved_items', type_='foreignkey')
    op.create_foreign_key(op.f('user_saved_items_user_id_fkey'), 'user_saved_items', 'users', ['user_id'], ['id'])
    op.drop_index('ix_user_saved_items_user_content', table_name='user_saved_items')
    op.drop_index(op.f('ix_user_saved_items_id'), table_name='user_saved_items')
    # ### end Alembic commands ###
