"""added nickname to user med

Revision ID: c94acad4d358
Revises: ddc45a0088a7
Create Date: 2026-02-26 17:22:48.086146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94acad4d358'
down_revision: Union[str, Sequence[str], None] = 'ddc45a0088a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_medications', sa.Column('nickname', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_medications', 'nickname')
    # ### end Alembic commands ###
