"""latest_id_fix_attempt1

Revision ID: d4d62239362c
Revises: afd12fe96ba2
Create Date: 2025-12-02 17:26:31.243457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d62239362c'
down_revision: Union[str, Sequence[str], None] = 'afd12fe96ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column("drug_index", sa.Column("latest_detail_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_drug_index_latest_detail",
        "drug_index", "drug_details",
        ["latest_detail_id"], ["id"],
        ondelete="SET NULL",
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
