"""symptom log reference user med

Revision ID: d83a3d0759e9
Revises: c94acad4d358
Create Date: 2026-03-06 16:31:40.545054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83a3d0759e9'
down_revision: Union[str, Sequence[str], None] = 'c94acad4d358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symptom_logs', sa.Column('user_medication_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_symptom_logs_medication_id'), table_name='symptom_logs')
    op.create_index(op.f('ix_symptom_logs_user_medication_id'), 'symptom_logs', ['user_medication_id'], unique=False)
    op.drop_constraint(op.f('symptom_logs_medication_id_fkey'), 'symptom_logs', type_='foreignkey')
    op.create_foreign_key(None, 'symptom_logs', 'user_medications', ['user_medication_id'], ['id'], ondelete='SET NULL')
    op.drop_column('symptom_logs', 'medication_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symptom_logs', sa.Column('medication_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'symptom_logs', type_='foreignkey')
    op.create_foreign_key(op.f('symptom_logs_medication_id_fkey'), 'symptom_logs', 'medications', ['medication_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_symptom_logs_user_medication_id'), table_name='symptom_logs')
    op.create_index(op.f('ix_symptom_logs_medication_id'), 'symptom_logs', ['medication_id'], unique=False)
    op.drop_column('symptom_logs', 'user_medication_id')
    # ### end Alembic commands ###
