"""added drug index to user medication

Revision ID: ddc45a0088a7
Revises: f26229d1f055
Create Date: 2026-02-18 17:13:44.818710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc45a0088a7'
down_revision: Union[str, Sequence[str], None] = 'f26229d1f055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug_details', 'drug_index_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('uq_drug_detail_name_eff_source'), 'drug_details', type_='unique')
    op.create_unique_constraint('uq_drugindex_eff_source', 'drug_details', ['drug_index_id', 'effective_time', 'source'])
    op.drop_constraint(op.f('drug_details_drug_index_id_fkey'), 'drug_details', type_='foreignkey')
    op.create_foreign_key(None, 'drug_details', 'drug_index', ['drug_index_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drug_details', type_='foreignkey')
    op.create_foreign_key(op.f('drug_details_drug_index_id_fkey'), 'drug_details', 'drug_index', ['drug_index_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_drugindex_eff_source', 'drug_details', type_='unique')
    op.create_unique_constraint(op.f('uq_drug_detail_name_eff_source'), 'drug_details', ['normalized_name', 'effective_time', 'source'], postgresql_nulls_not_distinct=False)
    op.alter_column('drug_details', 'drug_index_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
