"""added external_drug_updates

Revision ID: dee655388704
Revises: 5f2bebce8694
Create Date: 2026-04-03 11:42:31.786342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee655388704'
down_revision: Union[str, Sequence[str], None] = '5f2bebce8694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('external_drug_updates', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    op.alter_column('external_drug_updates', 'drug_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_external_drug_updates_drug_name'), table_name='external_drug_updates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_external_drug_updates_drug_name'), 'external_drug_updates', ['drug_name'], unique=False)
    op.alter_column('external_drug_updates', 'drug_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('external_drug_updates', 'external_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
