"""rename nickname to name user_medication

Revision ID: f26229d1f055
Revises: 41524d373cf5
Create Date: 2026-02-04 17:03:12.001532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26229d1f055'
down_revision: Union[str, Sequence[str], None] = '41524d373cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_medications', sa.Column('name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'user_medications', 'drug_details', ['drug_detail_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_medications', 'nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_medications', sa.Column('nickname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_medications', type_='foreignkey')
    op.drop_column('user_medications', 'name')
    # ### end Alembic commands ###
