"""edited table

Revision ID: f404885616fd
Revises: 888c77b4b826
Create Date: 2026-01-10 14:34:42.934838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f404885616fd'
down_revision: Union[str, Sequence[str], None] = '888c77b4b826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_details', sa.Column('stop_using_warnings', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('drug_details', sa.Column('upc_code', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'symptom_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_medications', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'user_medications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_medications', type_='foreignkey')
    op.alter_column('user_medications', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(None, 'symptom_logs', type_='foreignkey')
    op.drop_column('drug_details', 'upc_code')
    op.drop_column('drug_details', 'stop_using_warnings')
    # ### end Alembic commands ###
