# app/util/safety_warning_terms.py

WARNING_TERMS = {
    "allergy": [
        "allergic reaction",
        "allergy alert",
        "hives",
        "facial swelling",
        "swelling of the face",
        "itching",
        "rash",
        "blisters",
        "trouble breathing",
        "shortness of breath",
        "wheezing",
    ],
    "liver": [
        "liver damage",
        "liver warning",
        "severe liver damage",
        "liver problems",
        "liver disease",
        "dark urine",
        "yellowing of skin",
        "yellowing of eyes",
    ],
    "stomach bleeding": [
        "stomach bleeding",
        "bleeding problems",
        "black or bloody stools",
        "vomit blood",
        "bloody stools",
        "black stools",
    ],
    "heart": [
        "heart attack",
        "heart failure",
        "chest pain",
        "stroke",
        "high blood pressure",
        "irregular heartbeat",
        "rapid heartbeat",
    ],
    "pregnancy": [
        "pregnant",
        "pregnancy",
        "breast-feeding",
        "breastfeeding",
        "ask a health professional before use",
    ],
    "overdose": [
        "overdose warning",
        "poison control center",
        "get medical help right away",
        "in case of overdose",
    ],
    "children": [
        "children under",
        "ask a doctor before use in children",
        "keep out of reach of children",
    ],
    "drug interactions": [
        "ask a doctor or pharmacist before use if you are taking",
        "taking a blood thinning drug",
        "anticoagulant",
        "steroid drug",
        "other drugs containing",
        "prescription or nonprescription",
        "drug interactions",
    ],
    "driving or drowsiness": [
        "drowsiness",
        "do not drive",
        "avoid alcoholic drinks",
        "operate machinery",
        "sedatives or tranquilizers",
    ],
    "when to stop use": [
        "stop use and ask a doctor",
        "seek medical help right away",
        "pain gets worse",
        "fever gets worse",
        "new symptoms occur",
        "redness or swelling is present",
    ],
}